version: "3.9"

services:
  frontend:
    build: ./frontend

  backend:
    build: .
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  